{% set name = "pytest-textual-snapshot" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name | replace("-", "_") }}/{{ name | replace("-", "_") }}-{{ version }}.tar.gz
  sha256: 96d48ab01306852a3b4ae165f008d5fdd7fda777e91e9d2c3ea0f7d7458544eb

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry-core >=1.0.0
  run:
    - python >={{ python_min }}
    - pytest >=8.0.0
    - rich >=12.0.0
    - textual >=0.28.0
    - syrupy 4.8.0
    - jinja2 >=3.0.0

test:
  commands:
    - python test.py
  files:
    - test.py
  requires:
    - python {{ python_min }}

about:
  home: https://github.com/Textualize/pytest-textual-snapshot
  summary: A pytest plugin for snapshot testing Textual applications.
  description: |
    A pytest-textual-snapshot test saves an SVG screenshot of a running Textual app to disk.
    The next time the test runs, it takes another screenshot and compares it to the saved one. If the new screenshot differs from the old one, the test fails.
    This is a convenient way to quickly and automatically detect visual regressions in your applications.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - claudiushaag
